routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resources([
        'items' => 'ItemController'
    ]);
});

app/Item.php
<?php

namespace App;

use App\Traits\Changeable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Item extends Model
{
    use Changeable;

    protected $changeableFields = ['name', 'key'];

    /**
     * @var array
     */
    protected $fillable = ['name', 'key'];

    protected $hidden = ['user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\StoreItemRequest;
use App\Http\Resources\ItemCollection;
use App\Item;
use App\Services\ItemService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpFoundation\Response;

class ItemController extends Controller
{
    /**
     * @var ItemService
     */
    private $itemService;

    /**
     * ItemController constructor.
     * @param ItemService $itemService
     * @param Item $item
     */
    public function __construct(ItemService $itemService, Item $item)
    {
        $this->middleware('auth:api');
        $this->itemService = $itemService;
        $this->authorizeResource(Item::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return new ItemCollection($this->itemService->currentUserItemPaginate());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemRequest $request)
    {
        if ($this->itemService->create($request->validated())) {
            return response()->json([], Response::HTTP_CREATED);
        }

        return response()->json([], Response::HTTP_INTERNAL_SERVER_ERROR);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return new \App\Http\Resources\Item($item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function update(StoreItemRequest $request, Item $item)
    {
        if ($this->itemService->update($item, $request->validated())) {
            return response()->json([], Response::HTTP_OK);
        }
        return response()->json([], Response::HTTP_INTERNAL_SERVER_ERROR);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        if ($this->itemService->destroy($item)) {
            return response()->json([], Response::HTTP_NO_CONTENT);
        }
        return response()->json([], Response::HTTP_INTERNAL_SERVER_ERROR);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreItemRequest;
use App\Http\Requests\UpdateItemRequest;
use App\Item;
use App\Services\ItemService;
use App\User;
use Auth;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * @var ItemService
     */
    private $itemService;

    /**
     * ItemController constructor.
     * @param ItemService $itemService
     */
    public function __construct(ItemService $itemService)
    {
        $this->itemService = $itemService;
        $this->authorizeResource(Item::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Auth::user()->items()->paginate();
        return view('items.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('items.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreItemRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemRequest $request)
    {
        $this->itemService->create($request->validated());

        return redirect()->route('items.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        $item = $item->load('changes', 'changes.user');
        return view('items.view', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('items.form', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function update(StoreItemRequest $request, Item $item)
    {
        $this->itemService->update($item, $request->validated());
        return response()->redirectToRoute('items.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $this->itemService->destroy($item);
        return response()->redirectToRoute('items.index');
    }
}

resources/views/items/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <form method="post"
                      action="{{ isset($item) ? route('items.update', $item->id) : route('items.store') }}">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" aria-describedby="emailHelp"
                               placeholder="Enter name" name="name"
                               value="{{ isset($item) && null === old('name') ? $item->name : old('name') }}">
                        @if ($errors->has('name'))
                            <small class="form-text text-muted">{{ $errors->first('name') }}</small>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="key">Key</label>
                        <input type="text" class="form-control" id="key" placeholder="Enter key(max 25)" name="key"
                               value="{{ isset($item) && null === old('key') ? $item->key : old('key') }}">
                        @if ($errors->has('key'))
                            <small class="form-text text-muted">{{ $errors->first('key') }}</small>
                        @endif
                    </div>
                    <button type="submit" class="btn btn-primary">@if(isset($item)) Обновить @else Добавить @endif</button>
                    @csrf
                    @if(isset($item))
                        @method('PUT')
                    @endif
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 justify-content-end d-flex">
                <a class="btn btn-primary d-flex mb-1" href="{{ route('items.create') }}" role="button">Добавить
                    предмет</a>
            </div>
            <div class="col-md-12">
                @if(isset($items) && count($items) > 0)
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">First</th>
                            <th scope="col">Last</th>
                            <th scope="col">Handle</th>
                            <th scope="col">Handle</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($items as $item)
                            <tr>
                                <th>{{ $item->id }}</th>
                                <td><a href="{{ route('items.show', $item->id) }}">{{ str_limit($item->name, 25) }}</a>
                                </td>
                                <td>{{ str_limit($item->key, 15) }}</td>
                                <td>{{ $item->created_at }}</td>
                                <td>{{ $item->updated_at }}</td>
                                <td><a href="{{ route('items.edit', $item->id) }}"
                                       class="btn btn-link">Редактировать</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @else
                    <div class="h4 text-center">Записи не найдены</div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/items/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="h3">Информация о предмете</p>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-2 text-right">
                        <p class="h5">Name:</p>
                    </div>
                    <div class="col-10">
                        <p>{{ $item->name }}</p>
                    </div>
                    <div class="col-2 text-right">
                        <p class="h5">Key:</p>
                    </div>
                    <div class="col-10">
                        <p>{{ $item->key }}</p>
                    </div>
                </div>
                @can('update', $item)
                    <div class="">
                        <form action="{{ route('items.destroy', $item->id) }}" method="post">
                            <a href="{{ route('items.edit', $item->id) }}" class="btn btn-warning">Редактировать</a>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            @method('delete')
                            @csrf
                        </form>
                    </div>
                @endcan
            </div>
        </div>
        @if(count($item->changes) > 0)
            <div class="row">
                <div class="col-md-12 text-center mt-2 mb-1">
                    <p class="h3">Изменения предмета</p>
                </div>
            </div>
            <div class="row">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Имя пользователя</th>
                        <th scope="col">Поле</th>
                        <th scope="col">Старое значение</th>
                        <th scope="col">Новое значение</th>
                        <th scope="col">IP</th>
                        <th scope="col">Дата</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($item->changes as $change)
                        @foreach($change->old_value as $field => $value)
                            <tr>
                                <td>{{ $change->user->name }}</td>
                                <td>{{ $field }}</td>
                                <td>{{ $change->old_value[$field] }}</td>
                                <td>{{ $change->new_value[$field] }}</td>
                                <td>{{ $change->ip }}</td>
                                <td>{{ $change->created_at }}</td>
                            </tr>
                        @endforeach
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
@endsection